export const appointmentQueue= [
  {
  id: 1,
  token: "RAD001",
  patientName: "Rahul Sharma",
  uhid: "UH100245",
  age: 36,
  gender: "Male",
  modality: "CT",
  procedure: "CT Brain",
  radiologist: "Dr. Mehta",
  appointmentDate: "2026-07-23",
  appointmentTime: "09:30 AM",
  priority: "Emergency",
  status: "Queue",
},
{
  id: 2,
  token: "RAD002",
  patientName: "Priya Singh",
  uhid: "UH100312",
  age: 42,
  gender: "Female",
  modality: "MRI",
  procedure: "MRI Spine",
  radiologist: "Dr. Sharma",
  appointmentDate: "2026-07-23",
  appointmentTime: "09:45 AM",
  priority: "Urgent",
  status: "Queue",
},
{
  id: 3,
  token: "RAD003",
  patientName: "Amit Verma",
  uhid: "UH100489",
  age: 51,
  gender: "Male",
  modality: "X-Ray",
  procedure: "Chest PA View",
  radiologist: "Dr. Gupta",
  appointmentDate: "2026-07-23",
  appointmentTime: "10:00 AM",
  priority: "Routine",
  status: "Queue",
},
{
  id: 4,
  token: "RAD004",
  patientName: "Sneha Kapoor",
  uhid: "UH100521",
  age: 28,
  gender: "Female",
  modality: "Ultrasound",
  procedure: "Whole Abdomen",
  radiologist: "Dr. Nair",
  appointmentDate: "2026-07-23",
  appointmentTime: "10:20 AM",
  priority: "Routine",
  status: "Queue",
},
{
  id: 5,
  token: "RAD005",
  patientName: "Vikram Joshi",
  uhid: "UH100588",
  age: 61,
  gender: "Male",
  modality: "CT",
  procedure: "CT Chest",
  radiologist: "Dr. Mehta",
  appointmentDate: "2026-07-23",
  appointmentTime: "10:35 AM",
  priority: "Urgent",
  status: "Queue",
},
{
  id: 6,
  token: "RAD006",
  patientName: "Anjali Patel",
  uhid: "UH100604",
  age: 34,
  gender: "Female",
  modality: "MRI",
  procedure: "MRI Knee",
  radiologist: "Dr. Sharma",
  appointmentDate: "2026-07-23",
  appointmentTime: "10:50 AM",
  priority: "Routine",
  status: "Queue",
},
{
  id: 7,
  token: "RAD007",
  patientName: "Rohit Malhotra",
  uhid: "UH100622",
  age: 47,
  gender: "Male",
  modality: "X-Ray",
  procedure: "Lumbar Spine AP/LAT",
  radiologist: "Dr. Gupta",
  appointmentDate: "2026-07-23",
  appointmentTime: "11:05 AM",
  priority: "Routine",
  status: "Queue",
},
{
  id: 8,
  token: "RAD008",
  patientName: "Neha Arora",
  uhid: "UH100645",
  age: 39,
  gender: "Female",
  modality: "Mammography",
  procedure: "Screening Mammography",
  radiologist: "Dr. Kapoor",
  appointmentDate: "2026-07-23",
  appointmentTime: "11:20 AM",
  priority: "Routine",
  status: "Completed",
},
{
  id: 9,
  token: "RAD009",
  patientName: "Arjun Kumar",
  uhid: "UH100667",
  age: 54,
  gender: "Male",
  modality: "CT",
  procedure: "CT Abdomen",
  radiologist: "Dr. Mehta",
  appointmentDate: "2026-07-23",
  appointmentTime: "11:40 AM",
  priority: "Emergency",
  status: "Scan Started",
},
{
  id: 10,
  token: "RAD010",
  patientName: "Pooja Sharma",
  uhid: "UH100690",
  age: 31,
  gender: "Female",
  modality: "Ultrasound",
  procedure: "Pelvis Scan",
  radiologist: "Dr. Nair",
  appointmentDate: "2026-07-23",
  appointmentTime: "12:00 PM",
  priority: "Routine",
  status: "Queue",
},
];