/**
 * Ordering. There is no catalog table in the schema, so nothing here resolves a
 * catalog id: the picker offers name suggestions and the chosen text is written
 * to the department detail row (lab_order_items.test_name,
 * radiology_order_items.scan_type, procedures.procedure_name).
 */
import { labTestNames, placedOrders, procedureNames, radiologyScanTypes } from "@/lib/mock";
import type { CreateOrderInput, OrderType, PlacedOrder } from "../types";

function delay<T>(value: T, ms = 220): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(structuredClone(value)), ms));
}

const SUGGESTIONS: Record<OrderType, string[]> = {
  lab: labTestNames,
  radiology: radiologyScanTypes,
  procedure: procedureNames,
  /** Not placed from the OPD doctor panel — schema OrderType includes these. */
  pharmacy: [],
  blood: [],
};

/** Name suggestions only — free text is allowed, because the column is free text. */
export async function suggestOrderNames(type: OrderType, query = ""): Promise<string[]> {
  const q = query.trim().toLowerCase();
  const rows = SUGGESTIONS[type];
  return delay(q ? rows.filter((r) => r.toLowerCase().includes(q)) : rows);
}

const pad = (n: number, w: number) => String(n).padStart(w, "0");
const stamp = () => new Date().toISOString().slice(0, 10).replace(/-/g, "");

/**
 * POST /api/v1/orders — the order header, plus the department detail row.
 * The accession number is generated by the department (LAB-…/RAD-…) and is what
 * the patient and the lab will quote back, so the doctor needs to see it.
 */
export async function createOrder(input: CreateOrderInput): Promise<PlacedOrder> {
  placedOrders.push(input);
  const seq = placedOrders.length;
  const label =
    input.order_type === "lab"
      ? (input.test_name ?? "Lab test")
      : input.order_type === "radiology"
        ? (input.scan_type ?? "Study")
        : (input.procedure_name ?? "Procedure");

  return delay({
    id: crypto.randomUUID(),
    order_number: `ORD-${stamp()}-${pad(seq, 6)}`,
    order_type: input.order_type,
    priority: input.priority,
    status: "placed",
    ordered_at: new Date().toISOString(),
    accession_number:
      input.order_type === "lab"
        ? `LAB-${stamp()}-${pad(seq, 5)}`
        : input.order_type === "radiology"
          ? `RAD-${stamp()}-${pad(seq, 5)}`
          : undefined,
    item_label: label,
  });
}
