export type ProductStatus = "In Stock" | "Low Stock" | "Out of Stock";

export type Product = {
  id: string;
  sku: string;
  name: string;
  category: string;
  subCategory: string;
  manufacturer: string;
  unit: string;
  quantity: number;
  reorderLevel: number;
  purchaseRate: number;
  mrp: number;
  location: string;
};

export const PRODUCT_CATEGORIES = [
  "Medicines",
  "IV Fluids",
  "Medical Consumables",
  "Surgical Supplies",
  "Medical Equipment",
  "Laboratory Supplies",
  "PPE & Infection Control",
  "Ward & Furniture",
  "IT & General",
] as const;

export const BASE_PRODUCTS: Product[] = [
  // Medicines
  {
    id: "prd-1",
    sku: "MED-0001",
    name: "Augmentin 625 mg",
    category: "Medicines",
    subCategory: "Antibiotic · Tablet",
    manufacturer: "GSK",
    unit: "tablets",
    quantity: 28,
    reorderLevel: 40,
    purchaseRate: 14.5,
    mrp: 18,
    location: "Pharmacy / Rack A-03",
  },
  {
    id: "prd-2",
    sku: "MED-0002",
    name: "Dolo 650 mg",
    category: "Medicines",
    subCategory: "Analgesic · Tablet",
    manufacturer: "Micro Labs",
    unit: "tablets",
    quantity: 540,
    reorderLevel: 100,
    purchaseRate: 1.45,
    mrp: 2.1,
    location: "Pharmacy / Rack B-01",
  },
  {
    id: "prd-3",
    sku: "MED-0003",
    name: "Huminsulin 30/70 100 IU/ml",
    category: "Medicines",
    subCategory: "Insulin · Injection",
    manufacturer: "Eli Lilly",
    unit: "vials",
    quantity: 12,
    reorderLevel: 15,
    purchaseRate: 465,
    mrp: 510,
    location: "Cold Store / C-02",
  },
  {
    id: "prd-4",
    sku: "MED-0004",
    name: "Azithral 500 mg",
    category: "Medicines",
    subCategory: "Antibiotic · Tablet",
    manufacturer: "Alembic",
    unit: "tablets",
    quantity: 65,
    reorderLevel: 30,
    purchaseRate: 17,
    mrp: 21,
    location: "Pharmacy / Rack A-07",
  },
  {
    id: "prd-5",
    sku: "MED-0005",
    name: "Adrenaline 1 mg/ml",
    category: "Medicines",
    subCategory: "Emergency · Injection",
    manufacturer: "Neon Labs",
    unit: "ampoules",
    quantity: 96,
    reorderLevel: 50,
    purchaseRate: 9.8,
    mrp: 14,
    location: "Emergency Drug Store",
  },
  {
    id: "prd-6",
    sku: "MED-0006",
    name: "Betadine Ointment 5%",
    category: "Medicines",
    subCategory: "Antiseptic · Ointment",
    manufacturer: "Win-Medicare",
    unit: "tubes",
    quantity: 34,
    reorderLevel: 20,
    purchaseRate: 88,
    mrp: 105,
    location: "Pharmacy / Rack C-05",
  },
  {
    id: "prd-7",
    sku: "MED-0007",
    name: "Hydrocortisone 100 mg",
    category: "Medicines",
    subCategory: "Steroid · Injection",
    manufacturer: "Pfizer",
    unit: "vials",
    quantity: 0,
    reorderLevel: 25,
    purchaseRate: 42,
    mrp: 55,
    location: "Emergency Drug Store",
  },

  // IV Fluids
  {
    id: "prd-8",
    sku: "IVF-0001",
    name: "Normal Saline 0.9% 500 ml",
    category: "IV Fluids",
    subCategory: "Crystalloid",
    manufacturer: "Baxter",
    unit: "bottles",
    quantity: 420,
    reorderLevel: 100,
    purchaseRate: 42,
    mrp: 55,
    location: "Bulk Store / Bay 04",
  },
  {
    id: "prd-9",
    sku: "IVF-0002",
    name: "Ringer Lactate 500 ml",
    category: "IV Fluids",
    subCategory: "Crystalloid",
    manufacturer: "B. Braun",
    unit: "bottles",
    quantity: 260,
    reorderLevel: 80,
    purchaseRate: 46,
    mrp: 60,
    location: "Bulk Store / Bay 05",
  },
  {
    id: "prd-10",
    sku: "IVF-0003",
    name: "Dextrose 5% 500 ml",
    category: "IV Fluids",
    subCategory: "Dextrose Solution",
    manufacturer: "Baxter",
    unit: "bottles",
    quantity: 64,
    reorderLevel: 70,
    purchaseRate: 44,
    mrp: 58,
    location: "Bulk Store / Bay 05",
  },
  {
    id: "prd-11",
    sku: "IVF-0004",
    name: "Sterile Water for Injection 10 ml",
    category: "IV Fluids",
    subCategory: "Diluent",
    manufacturer: "Nirma Healthcare",
    unit: "ampoules",
    quantity: 800,
    reorderLevel: 200,
    purchaseRate: 6,
    mrp: 9,
    location: "Pharmacy / Rack D-02",
  },

  // Medical Consumables
  {
    id: "prd-12",
    sku: "CON-0001",
    name: "IV Cannula 20G",
    category: "Medical Consumables",
    subCategory: "IV & Injection",
    manufacturer: "BD",
    unit: "pieces",
    quantity: 350,
    reorderLevel: 150,
    purchaseRate: 22,
    mrp: 32,
    location: "Consumable Store / C-01",
  },
  {
    id: "prd-13",
    sku: "CON-0002",
    name: "Syringe 10 ml",
    category: "Medical Consumables",
    subCategory: "IV & Injection",
    manufacturer: "Dispovan",
    unit: "pieces",
    quantity: 1200,
    reorderLevel: 400,
    purchaseRate: 4.2,
    mrp: 7,
    location: "Consumable Store / C-02",
  },
  {
    id: "prd-14",
    sku: "CON-0003",
    name: "Sterile Gauze Pads",
    category: "Medical Consumables",
    subCategory: "Dressing & Wound Care",
    manufacturer: "SurgiCare",
    unit: "packs",
    quantity: 90,
    reorderLevel: 100,
    purchaseRate: 35,
    mrp: 48,
    location: "Dressing Room Store",
  },
  {
    id: "prd-15",
    sku: "CON-0004",
    name: "Oxygen Mask (Adult)",
    category: "Medical Consumables",
    subCategory: "Airway & Oxygen",
    manufacturer: "Romsons",
    unit: "pieces",
    quantity: 140,
    reorderLevel: 60,
    purchaseRate: 38,
    mrp: 55,
    location: "Resuscitation Bay Store",
  },
  {
    id: "prd-16",
    sku: "CON-0005",
    name: "Endotracheal Tube 7.5",
    category: "Medical Consumables",
    subCategory: "Airway & Oxygen",
    manufacturer: "Portex",
    unit: "pieces",
    quantity: 45,
    reorderLevel: 30,
    purchaseRate: 96,
    mrp: 130,
    location: "Resuscitation Bay Store",
  },
  {
    id: "prd-17",
    sku: "CON-0006",
    name: "ECG Electrodes",
    category: "Medical Consumables",
    subCategory: "Diagnostic",
    manufacturer: "3M",
    unit: "pieces",
    quantity: 600,
    reorderLevel: 250,
    purchaseRate: 8,
    mrp: 12,
    location: "Emergency Diagnostic Store",
  },

  // Surgical Supplies
  {
    id: "prd-18",
    sku: "SUR-0001",
    name: "Vicryl 2-0 Suture",
    category: "Surgical Supplies",
    subCategory: "Sutures",
    manufacturer: "Ethicon",
    unit: "packs",
    quantity: 85,
    reorderLevel: 40,
    purchaseRate: 310,
    mrp: 380,
    location: "OT Store / Rack S-05",
  },
  {
    id: "prd-19",
    sku: "SUR-0002",
    name: "Surgical Blade No. 22",
    category: "Surgical Supplies",
    subCategory: "Blades & Instruments",
    manufacturer: "Swann-Morton",
    unit: "pieces",
    quantity: 480,
    reorderLevel: 200,
    purchaseRate: 6,
    mrp: 10,
    location: "OT Store / Rack S-02",
  },
  {
    id: "prd-20",
    sku: "SUR-0003",
    name: "Laparotomy Sponge",
    category: "Surgical Supplies",
    subCategory: "Sponges",
    manufacturer: "SurgiCare",
    unit: "pieces",
    quantity: 240,
    reorderLevel: 100,
    purchaseRate: 18,
    mrp: 26,
    location: "OT Store / Rack S-01",
  },
  {
    id: "prd-21",
    sku: "SUR-0004",
    name: "Titanium Hip Stem Implant",
    category: "Surgical Supplies",
    subCategory: "Implants",
    manufacturer: "OrthoMed",
    unit: "implants",
    quantity: 1,
    reorderLevel: 1,
    purchaseRate: 96000,
    mrp: 128000,
    location: "OT Store / Implant Safe A",
  },
  {
    id: "prd-22",
    sku: "SUR-0005",
    name: "Cervical Collar (Adjustable)",
    category: "Surgical Supplies",
    subCategory: "Trauma",
    manufacturer: "Tynor",
    unit: "pieces",
    quantity: 26,
    reorderLevel: 15,
    purchaseRate: 240,
    mrp: 320,
    location: "Trauma Bay Store",
  },

  // Medical Equipment
  {
    id: "prd-23",
    sku: "EQP-0001",
    name: "Defibrillator",
    category: "Medical Equipment",
    subCategory: "Resuscitation",
    manufacturer: "Philips",
    unit: "units",
    quantity: 4,
    reorderLevel: 2,
    purchaseRate: 385000,
    mrp: 450000,
    location: "Emergency Equipment Bay",
  },
  {
    id: "prd-24",
    sku: "EQP-0002",
    name: "Multiparameter Patient Monitor",
    category: "Medical Equipment",
    subCategory: "Monitoring",
    manufacturer: "Mindray",
    unit: "units",
    quantity: 12,
    reorderLevel: 4,
    purchaseRate: 145000,
    mrp: 178000,
    location: "Biomedical Store",
  },
  {
    id: "prd-25",
    sku: "EQP-0003",
    name: "Infusion Pump",
    category: "Medical Equipment",
    subCategory: "Infusion",
    manufacturer: "B. Braun",
    unit: "units",
    quantity: 9,
    reorderLevel: 5,
    purchaseRate: 68000,
    mrp: 82000,
    location: "Biomedical Store",
  },
  {
    id: "prd-26",
    sku: "EQP-0004",
    name: "Portable Ventilator",
    category: "Medical Equipment",
    subCategory: "Respiratory",
    manufacturer: "Dräger",
    unit: "units",
    quantity: 2,
    reorderLevel: 2,
    purchaseRate: 520000,
    mrp: 610000,
    location: "Emergency Equipment Bay",
  },
  {
    id: "prd-27",
    sku: "EQP-0005",
    name: "Pulse Oximeter",
    category: "Medical Equipment",
    subCategory: "Monitoring",
    manufacturer: "Nellcor",
    unit: "units",
    quantity: 30,
    reorderLevel: 10,
    purchaseRate: 2200,
    mrp: 3200,
    location: "Ward Supply Store",
  },

  // Laboratory Supplies
  {
    id: "prd-28",
    sku: "LAB-0001",
    name: "Blood Collection Tubes (EDTA)",
    category: "Laboratory Supplies",
    subCategory: "Sample Collection",
    manufacturer: "BD Vacutainer",
    unit: "pieces",
    quantity: 1500,
    reorderLevel: 500,
    purchaseRate: 9,
    mrp: 14,
    location: "Laboratory Store",
  },
  {
    id: "prd-29",
    sku: "LAB-0002",
    name: "Rapid Malaria Test Kit",
    category: "Laboratory Supplies",
    subCategory: "Rapid Diagnostics",
    manufacturer: "SD Biosensor",
    unit: "kits",
    quantity: 75,
    reorderLevel: 50,
    purchaseRate: 85,
    mrp: 120,
    location: "Laboratory Store",
  },
  {
    id: "prd-30",
    sku: "LAB-0003",
    name: "Biochemistry Reagent Pack",
    category: "Laboratory Supplies",
    subCategory: "Reagents",
    manufacturer: "Roche",
    unit: "packs",
    quantity: 18,
    reorderLevel: 20,
    purchaseRate: 5400,
    mrp: 6200,
    location: "Reagent Refrigerator",
  },
  {
    id: "prd-31",
    sku: "LAB-0004",
    name: "Urine Collection Containers",
    category: "Laboratory Supplies",
    subCategory: "Sample Collection",
    manufacturer: "Tarsons",
    unit: "pieces",
    quantity: 900,
    reorderLevel: 300,
    purchaseRate: 4,
    mrp: 7,
    location: "Laboratory Store",
  },

  // PPE & Infection Control
  {
    id: "prd-32",
    sku: "PPE-0001",
    name: "N95 Masks",
    category: "PPE & Infection Control",
    subCategory: "Respiratory Protection",
    manufacturer: "3M",
    unit: "pieces",
    quantity: 800,
    reorderLevel: 300,
    purchaseRate: 45,
    mrp: 65,
    location: "PPE Store",
  },
  {
    id: "prd-33",
    sku: "PPE-0002",
    name: "Sterile Surgical Gloves 7.5",
    category: "PPE & Infection Control",
    subCategory: "Hand Protection",
    manufacturer: "Ansell",
    unit: "pairs",
    quantity: 220,
    reorderLevel: 250,
    purchaseRate: 28,
    mrp: 40,
    location: "PPE Store",
  },
  {
    id: "prd-34",
    sku: "PPE-0003",
    name: "Disposable Gowns",
    category: "PPE & Infection Control",
    subCategory: "Body Protection",
    manufacturer: "Medline",
    unit: "pieces",
    quantity: 340,
    reorderLevel: 150,
    purchaseRate: 60,
    mrp: 85,
    location: "PPE Store",
  },
  {
    id: "prd-35",
    sku: "PPE-0004",
    name: "Hand Sanitizer 500 ml",
    category: "PPE & Infection Control",
    subCategory: "Disinfection",
    manufacturer: "Himalaya",
    unit: "bottles",
    quantity: 160,
    reorderLevel: 80,
    purchaseRate: 110,
    mrp: 150,
    location: "Utility Store",
  },
  {
    id: "prd-36",
    sku: "PPE-0005",
    name: "Sharps Containers 5L",
    category: "PPE & Infection Control",
    subCategory: "Waste Management",
    manufacturer: "BioSafe",
    unit: "pieces",
    quantity: 48,
    reorderLevel: 25,
    purchaseRate: 130,
    mrp: 180,
    location: "Utility Store",
  },

  // Ward & Furniture
  {
    id: "prd-37",
    sku: "WRD-0001",
    name: "Motorized ICU Bed",
    category: "Ward & Furniture",
    subCategory: "Beds",
    manufacturer: "Midmark",
    unit: "beds",
    quantity: 18,
    reorderLevel: 5,
    purchaseRate: 118000,
    mrp: 128000,
    location: "Central Store / Bay A1",
  },
  {
    id: "prd-38",
    sku: "WRD-0002",
    name: "Patient Wheelchair",
    category: "Ward & Furniture",
    subCategory: "Transport",
    manufacturer: "Karma",
    unit: "chairs",
    quantity: 9,
    reorderLevel: 6,
    purchaseRate: 12800,
    mrp: 14500,
    location: "Ward Supply Store / Zone B",
  },
  {
    id: "prd-39",
    sku: "WRD-0003",
    name: "Stretcher Trolley",
    category: "Ward & Furniture",
    subCategory: "Transport",
    manufacturer: "GPC Medical",
    unit: "units",
    quantity: 7,
    reorderLevel: 4,
    purchaseRate: 24500,
    mrp: 28000,
    location: "Emergency Department",
  },
  {
    id: "prd-40",
    sku: "WRD-0004",
    name: "Bedside Locker",
    category: "Ward & Furniture",
    subCategory: "Furniture",
    manufacturer: "Godrej Interio",
    unit: "lockers",
    quantity: 35,
    reorderLevel: 10,
    purchaseRate: 8400,
    mrp: 9200,
    location: "Furniture Store / Row C2",
  },

  // IT & General
  {
    id: "prd-41",
    sku: "ITG-0001",
    name: "Barcode Label Printer",
    category: "IT & General",
    subCategory: "IT Hardware",
    manufacturer: "Zebra",
    unit: "units",
    quantity: 6,
    reorderLevel: 2,
    purchaseRate: 18500,
    mrp: 22000,
    location: "LIS Work Area",
  },
  {
    id: "prd-42",
    sku: "ITG-0002",
    name: "UPS 2 kVA",
    category: "IT & General",
    subCategory: "Power Backup",
    manufacturer: "APC",
    unit: "units",
    quantity: 10,
    reorderLevel: 4,
    purchaseRate: 14200,
    mrp: 16800,
    location: "IT Store",
  },
  {
    id: "prd-43",
    sku: "ITG-0003",
    name: "AA Batteries",
    category: "IT & General",
    subCategory: "General Supplies",
    manufacturer: "Duracell",
    unit: "pieces",
    quantity: 40,
    reorderLevel: 60,
    purchaseRate: 22,
    mrp: 30,
    location: "General Store",
  },
  {
    id: "prd-44",
    sku: "ITG-0004",
    name: "Disposable Bed Sheets",
    category: "IT & General",
    subCategory: "General Supplies",
    manufacturer: "MediSafe",
    unit: "pieces",
    quantity: 500,
    reorderLevel: 200,
    purchaseRate: 32,
    mrp: 45,
    location: "General Store",
  },
];

const GENERATED_PRODUCT_SEEDS: Array<{
  category: (typeof PRODUCT_CATEGORIES)[number];
  subCategory: string;
  unit: string;
  manufacturer: string;
  names: string[];
}> = [
  {
    category: "Medicines",
    subCategory: "Oral Solid",
    unit: "tablets",
    manufacturer: "Cipla",
    names: [
      "Metformin 500 mg",
      "Amlodipine 5 mg",
      "Atorvastatin 10 mg",
      "Losartan 50 mg",
      "Pantoprazole 40 mg",
      "Cetirizine 10 mg",
      "Montelukast 10 mg",
      "Thyronorm 50 mcg",
      "Clopidogrel 75 mg",
      "Telmisartan 40 mg",
      "Glimipride 2 mg",
      "Rosuvastatin 20 mg",
    ],
  },
  {
    category: "IV Fluids",
    subCategory: "Infusion",
    unit: "bottles",
    manufacturer: "Baxter",
    names: [
      "DNS 500 ml",
      "RL 500 ml",
      "Dextrose 5% 500 ml",
      "Mannitol 20%",
      "Plasma-Lyte A",
      "Amino Acid Infusion",
      "Lipid Emulsion 20%",
      "Isolyte M",
    ],
  },
  {
    category: "Medical Consumables",
    subCategory: "Disposables",
    unit: "pieces",
    manufacturer: "BD",
    names: [
      "Syringe 2 ml",
      "Syringe 5 ml",
      "Syringe 10 ml",
      "IV Set Macro",
      "IV Set Micro",
      "Three-way Stopcock",
      "Extension Line 100 cm",
      "Urine Collection Bag",
      "Nebulizer Mask Adult",
      "Nebulizer Mask Ped",
      "Suction Catheter 12 Fr",
      "Nasogastric Tube 16 Fr",
    ],
  },
  {
    category: "Surgical Supplies",
    subCategory: "OT Consumables",
    unit: "packs",
    manufacturer: "Ethicon",
    names: [
      "Silk 1-0 Suture",
      "Nylon 3-0 Suture",
      "Skin Stapler",
      "Hemostatic Sponges",
      "Surgical Blade 11",
      "Surgical Blade 22",
      "Sterile Gown L",
      "OT Drape Pack",
      "Bone Wax",
      "Ligating Clips",
    ],
  },
  {
    category: "Laboratory Supplies",
    subCategory: "Reagents & Consumables",
    unit: "kits",
    manufacturer: "Roche",
    names: [
      "CBC Reagent Pack",
      "LFT Reagent Pack",
      "RFT Reagent Pack",
      "Lipid Profile Kit",
      "HbA1c Kit",
      "Blood Culture Bottle Aerobic",
      "Vacutainer EDTA",
      "Vacutainer Plain",
      "Urine Container Sterile",
      "Rapid Troponin Kit",
    ],
  },
  {
    category: "PPE & Infection Control",
    subCategory: "PPE",
    unit: "pieces",
    manufacturer: "3M",
    names: [
      "N95 Mask Pack",
      "Face Shield",
      "Isolation Gown",
      "Shoe Cover Box",
      "Head Cap Box",
      "Hand Rub 5L",
      "Surface Disinfectant 5L",
      "Biohazard Bags",
    ],
  },
  {
    category: "Medical Equipment",
    subCategory: "Accessories",
    unit: "units",
    manufacturer: "Philips",
    names: [
      "SpO2 Probe Adult",
      "NIBP Cuff Adult",
      "ECG Cable 5-Lead",
      "Defibrillator Pads",
      "Infusion Pump Set",
      "Ventilator Circuit Adult",
      "Thermometer Probe Cover",
      "Glucometer Strips",
    ],
  },
  {
    category: "Ward & Furniture",
    subCategory: "Ward Assets",
    unit: "units",
    manufacturer: "Hospital Care",
    names: [
      "Bedside Screen",
      "Overbed Table",
      "Patient Chair",
      "Crash Cart Drawer Kit",
      "Bed Extension Board",
      "Foot Stool",
    ],
  },
  {
    category: "IT & General",
    subCategory: "Stationery & IT",
    unit: "pieces",
    manufacturer: "OfficeMed",
    names: [
      "Thermal Paper 80mm",
      "Barcode Labels",
      "Printer Toner",
      "Patient File Folders",
      "ID Band Adult",
      "ID Band Pediatric",
    ],
  },
];

const GENERATED_PRODUCTS: Product[] = GENERATED_PRODUCT_SEEDS.flatMap(
  (seed, seedIndex) =>
    seed.names.map((name, nameIndex) => {
      const idNum = 100 + seedIndex * 20 + nameIndex;
      const quantityVariants = [0, 8, 18, 45, 120, 260, 540, 12, 3, 95];
      const quantity = quantityVariants[(seedIndex + nameIndex) % quantityVariants.length];
      const reorderLevel = 20 + ((seedIndex + nameIndex) * 7) % 80;
      const purchaseRate = 15 + ((seedIndex + nameIndex) * 13) % 400;
      return {
        id: `prd-${idNum}`,
        sku: `${seed.category.slice(0, 3).toUpperCase()}-${String(idNum).padStart(4, "0")}`,
        name,
        category: seed.category,
        subCategory: seed.subCategory,
        manufacturer: seed.manufacturer,
        unit: seed.unit,
        quantity,
        reorderLevel,
        purchaseRate,
        mrp: Math.round(purchaseRate * 1.25 * 100) / 100,
        location: [
          "Central Warehouse / Aisle 1",
          "Pharmacy / Rack D-02",
          "OT Store / Shelf 3",
          "Lab Store / Cold 1",
          "Emergency Bay / Rack E",
          "ICU Store / Cabinet 2",
          "General Store / Bay B",
        ][(seedIndex + nameIndex) % 7],
      } satisfies Product;
    }),
);

export const INITIAL_PRODUCTS: Product[] = [
  ...BASE_PRODUCTS,
  ...GENERATED_PRODUCTS,
];

export function productStatus(product: Product): ProductStatus {
  if (product.quantity === 0) return "Out of Stock";
  if (product.quantity <= product.reorderLevel) return "Low Stock";
  return "In Stock";
}
